name: Build Binaries

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  cross-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate docker image
        run: ./Shfile.sh make-image
      - name: Run cross-compilation
        run: ./Shfile.sh cross-compile
      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: dedoc-x86_64-linux-musl
          path: ./target-docker/x86_64-unknown-linux-musl/release/dedoc
      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: dedoc-x86_64-win32
          path: ./target-docker/x86_64-pc-windows-gnu/release/dedoc.exe
