name: Build binaries

on:
  release:
    types: [ created ]

jobs:
  cross-compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-musl, x86_64-pc-windows-gnu ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate docker image
        run: ./Shfile.sh make-image
      - name: Cross-compile for ${{ matrix.target }}
        run: ./Shfile.sh cross-compile
        env:
          TS: ${{ matrix.target }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dedoc-${{ matrix.target }}
          path: target-docker/${{ matrix.target }}/release/dedoc${{ endsWith(matrix.target, 'windows-gnu') && '.exe' || '' }}
