name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-image:
    uses: ./.github/workflows/build-image.yml
    permissions:
      contents: read
      packages: write
    with:
      watch_paths: |
        Dockerfile
        Shfile.sh

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull cached image
        run: |
          docker pull ${{ needs.docker.outputs.image }}
          docker tag ${{ needs.docker.outputs.image }} dedoc-rust-cross

      - name: Run tests
        run: ./Shfile.sh test

      - name: Collect summary
        run: cat ./integration-tests/coverage/report.md >> $GITHUB_STEP_SUMMARY
