name: Integration Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make image
        run: ./Shfile.sh make-image
      - name: Run tests
        run: ./Shfile.sh test
      - name: Collecting summary
        run: cat ./integration-tests/coverage/report.md >> $GITHUB_STEP_SUMMARY
