name: Integration Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make image
        run: ./Shfile.sh make-image
      - name: Run tests
        run: ./Shfile.sh test
      - name: View HTML report
        uses: michaelhenry/create-report@v2
        with:
          title: "HTML report"
          path: ./integration-tests/coverage/report/index.html
          format: html
